### PR TITLE
Update to newest XMPP4r

### PR DESCRIPTION
**Pull request by whatisgravity**

### CODE REVIEW

**Comment by badboy** [comment]
Did you test it with the latest versions?

**Comment by whatisgravity** [comment]
Yes, it works fine. No reason not to use the newest versions.

**Comment by badboy** [comment]
Alright then.

**Comment by whatisgravity** [comment]
Thanks for being flexible, now I don't need my own branch for my silly bot. 

Good work, I was right about to build my own but I like the level of complexity vs. simplicity in your library. It is a good balance.

**Pull request merged**
